/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */


export interface paths {
  "/iloq/keycontracts": {
    /**
     * Get list of key contracts
     * @description Gets list of all contracts with pagination.
     */
    get: operations["IloqController_getListOfContracts"];
    /**
     * Create a key contract
     * @description
     *  Creates a contract which will be synced to device(s).</br>
     *  If notification flag(s) are enabled, notifications will also be sent to the user.</br>
     *
     *
     *  Contract type defines the type of contract to be created. Depending on the contract type, different fields are required. </br>
     *  Different types of contracts: </br>
     *   `1` = default </br>
     *   `2` = fetch </br>
     *   `3` = return </br>
     *
     *   When creating return type contract, keys will be added to the system if they do not exist. </br>
     *
     *  Select contractType to see required fields. </br>
     */
    post: operations["IloqController_createContract"];
  };
  "/iloq/keycontracts/{id}": {
    /** Get contract by id */
    get: operations["IloqController_getContractById"];
    /**
     * Delete a key contract by id.
     * @description
     *   Delete a contract by id. </br></b>
     *
     *   Restrictions:</br>
     *   **Default** contract cannot be deleted if any key has been fetched but not yet returned. </br>
     *   **Fetch-only** contract cannot be deleted if some keys have been fetched while others are still waiting to be fetched. </br>
     *   **Return-only** contract cannot be deleted if some keys have been returned while others are still waiting to be returned. </br>
     */
    delete: operations["IloqController_deleteContractById"];
    /**
     * Update a key contract by id
     * @description
     *  Partially update one or more fields of a contract. </br>
     */
    patch: operations["IloqController_updateContractById"];
  };
  "/iloq/accessRights": {
    /** Get list of access rights */
    get: operations["IloqController_getAccessRights"];
  };
  "/automats": {
    /** Get list of automats */
    get: operations["AutomatsController_getAutomats"];
  };
  "/automats/{id}": {
    /** Get automat by id */
    get: operations["AutomatsController_getAutomatById"];
    /**
     * Update automat
     * @description Updates automat information
     */
    patch: operations["AutomatsController_updateAutomat"];
  };
  "/automats/install": {
    /**
     * Install automat
     * @description Installs a new key automat to LivionKey system.
     */
    post: operations["AutomatsController_installAutomat"];
  };
  "/automats/{id}/uninstall": {
    /**
     * Uninstall automat.
     * @description Sets device lifecycle state to deactivated.
     */
    post: operations["AutomatsController_uninstallAutomat"];
  };
  "/automats/{id}/replace": {
    /**
     * Replace automat
     * @description Replaces automat hwId with a new one
     */
    post: operations["AutomatsController_replaceAutomat"];
  };
  "/automats/{id}/sendPincode": {
    /**
     * Send pincode
     * @description Sends a pincode to the Key Automat.
     *     If the pincode matches one stored in the automat, the corresponding locker will open.
     *     In case of iLOQ S5 keys, the key will also be programmed with the access rights defined in the contract.
     */
    post: operations["AutomatsController_sendPincode"];
  };
  "/automats/{id}/cancelSendPincode": {
    /**
     * Cancel send pincode
     * @description Cancels a pincode send to the automat or any ongoing proximity check.
     *     Typically used to cancel previously sent sendPincode command with proximityCheck: true
     */
    post: operations["AutomatsController_cancelSendPincode"];
  };
  "/groups": {
    /**
     * Get list of groups
     * @description Gets list of all groups with pagination.
     */
    get: operations["GroupsController_list"];
    /** Create a new group */
    post: operations["GroupsController_create"];
  };
  "/groups/{id}": {
    /** Get group by id */
    get: operations["GroupsController_findOne"];
    /** Delete a group by id */
    delete: operations["GroupsController_delete"];
    /**
     * Update group
     * @description Updates group information
     */
    patch: operations["GroupsController_update"];
  };
  "/organizationUnits": {
    /**
     * Create a new organization unit
     * @description Create different types of organization units
     */
    post: operations["OrganizationUnitsController_create"];
  };
  "/serviceAccounts": {
    /**
     * Create a service account
     * @description Create a service account for organization unit. Note that the private key will be only shown once.
     */
    post: operations["ServiceAccountsController_create"];
  };
  "/serviceAccounts/{id}": {
    /** Delete a service account by id */
    delete: operations["ServiceAccountsController_delete"];
  };
  "/mechanical/keycontracts": {
    /**
     * List contracts
     * @description Get paginated list of contracts.
     */
    get: operations["list"];
    /**
     * Create a mechanical key contract
     * @description Create a mechanical key contract to hand over keys.
     */
    post: operations["create"];
  };
  "/mechanical/keycontracts/{id}": {
    /**
     * Get contract by id
     * @description Get contract by id
     */
    get: operations["get"];
    /**
     * Delete contract by id
     * @description Delete contract by id. Contract cannot be deleted if any key has been fetched but not yet returned.
     */
    delete: operations["delete"];
    /**
     * Update contract by id
     * @description Update contract by id. In some situations verification cannot be changed. <br> Note that when updating contact information, you need to provide full contact information object, not just the fields you want to change.
     */
    patch: operations["update"];
  };
  "/mechanical/keys": {
    /**
     * Paginated list of keys
     * @description Paginated list of keys
     */
    get: operations["list"];
    /**
     * Create a mechanical key
     * @description Create a mechanical key
     */
    post: operations["create"];
  };
  "/mechanical/keys/{id}": {
    /**
     * Get a key by id
     * @description Get a key by id
     */
    get: operations["get"];
    /**
     * Delete a key by id
     * @description Delete a key by id
     */
    delete: operations["delete"];
    /**
     * Update a key by id
     * @description Update a key by id
     */
    patch: operations["update"];
  };
}

export type webhooks = Record<string, never>;

export interface components {
  schemas: {
    NotificationChannelDto: {
      /**
       * @description Whether to send SMS notifications
       * @example false
       */
      sms: boolean;
      /**
       * @description Whether to send email notifications
       * @example false
       */
      email: boolean;
    };
    ContactNotificationsDto: {
      /** @description Notification settings for when a key is fetched */
      contractKeyFetched?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for when a key is returned */
      contractKeyReturned?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for when a contract is created */
      contractCreated?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for start date reminders */
      contractStartReminder?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for end date reminders */
      contractEndReminder?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for when keys are not returned */
      contractKeysNotReturned?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for when a contract is updated */
      contractUpdated?: components["schemas"]["NotificationChannelDto"];
      /** @description Notification settings for when signature is requested */
      contractSignatureRequested?: components["schemas"]["NotificationChannelDto"];
    };
    ContractContact: {
      /** @example John Doe */
      name: string;
      /** @example john.doe@livion.fi */
      email: string | null;
      /** @example +358401234567 */
      phoneNumber: string | null;
      /**
       * @description Look for notifications object to check what SMS notifications are sent.
       * @example true
       */
      sendSms: boolean;
      /**
       * @description Look for notifications object to check what email notifications are sent.
       * @example true
       */
      sendEmail: boolean;
      /**
       * @description Language code for the contact. Defines the language used for notifications
       * @example en | fi | sv | de | no | fr
       * @enum {string|null}
       */
      language: "en" | "fi" | "sv" | "de" | "no" | "fr" | null;
      /** @example f5ac6bce-eac9-4508-a5cf-a0114dc06477 */
      iloqPersonId: string | null;
      /**
       * @description Detailed notification settings that explicitly define which notifications will be sent and through which channels (SMS/email).
       * @example {
       *   "contractKeyFetched": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeyReturned": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractCreated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractStartReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractEndReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeysNotReturned": {
       *     "sms": false,
       *     "email": true
       *   },
       *   "contractUpdated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractSignatureRequested": {
       *     "sms": false,
       *     "email": false
       *   }
       * }
       */
      notifications: components["schemas"]["ContactNotificationsDto"];
    };
    IloqContractKeyStorageInfo: {
      /** @example 00331 */
      deviceId: string;
      /**
       * @description Pincode for the key. If they key is no longer usable for this contract, this field is null.
       * @example 233123
       */
      pincode: string | null;
    };
    IloqContractKey: {
      /** @example f5ac6bce-eac9-4508-a5cf-a0114dc06477 */
      id: string;
      /**
       * @description Status of the key
       * @example key-fetched
       */
      status: string | null;
      /**
       * @description Location where key is stored
       * @example {
       *   "deviceId": "00331",
       *   "pincode": "233123"
       * }
       */
      storageInfo: components["schemas"]["IloqContractKeyStorageInfo"];
      /**
       * @description Boolean flag which indicates whether the key has been moved to history due to being fetched (fetch contracts), returned (return contracts), reassigned to a new contract, removed, or blocklisted.
       *       If true, the key is in history and cannot be used anymore for this contract.
       * @example false
       */
      inHistory?: boolean;
    };
    IloqKeyContract: {
      /** @description Contract id */
      id: string;
      /** @description An array of iLOQ key access rights that will be programmed to the key when key is fetched */
      accessRightIds: (readonly string[]) | null;
      /**
       * Format: date-time
       * @description Start date of the contract
       */
      start: string;
      /**
       * Format: date-time
       * @description End date of the contract. If not set, the contract is treated as permanent.
       */
      end: string | null;
      /** @description Contact information of the recipient */
      contact: components["schemas"]["ContractContact"] | null;
      /** @description An array of keys that were selected for handover/return */
      keys: readonly components["schemas"]["IloqContractKey"][];
      /**
       * @description Amount of keys needed for the handover
       * @example 1
       */
      numberOfKeys: number | null;
      /** @description List of keyIds that are needed for the handover */
      keyIds: (readonly string[]) | null;
      /** @description Key automat device id from where the keys should be collected */
      keyAutomatId: string | null;
      /** @description Device group Id, configured in LivionKey system */
      groupId: string | null;
      /**
       * @description Contract type
       * @example 1
       */
      contractType: number;
    };
    ContactInput: {
      /** @example John Doe */
      name: string;
      /** @example john.doe@livion.fi */
      email?: string;
      /** @example +358401234567 */
      phoneNumber?: string;
      /**
       * @description Boolean flag defining if SMS should be sent to the contact or not. Will use organization default notification settings to determine if SMS should be sent for each notification type. NOTE: This field is only used if the notifications object is NOT provided. If the notifications object is provided, this field is ignored.
       * @example true
       */
      sendSms?: boolean;
      /**
       * @description Boolean flag defining if Email should be sent to the contact or not. Will use organization default notification settings to determine if Email should be sent for each notification type. NOTE: This field is only used if the notifications object is NOT provided. If the notifications object is provided, this field is ignored.
       * @example true
       */
      sendEmail?: boolean;
      /**
       * @description Language code for the contact. Defines the language used for notifications. Defaults to "en" if not provided.
       * @default en
       * @example en | fi | sv | de | no | fr
       * @enum {string}
       */
      language?: "en" | "fi" | "sv" | "de" | "no" | "fr";
      /**
       * @description Detailed notification settings for different event types. This field is optional - you only need to provide it when you want granular control over notifications.
       *
       * IMPORTANT: When this object is provided, the global sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * You can include only the specific notification types you want to customize. For notification types not included in this object, no notifications will be sent.
       *
       * You can also specify only sms or only email for each notification type - unspecified channels will default to false.
       *
       * BEST PRACTICES:
       * - Use this notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the 'contractKeysNotReturned' notification to ensure keys are properly tracked.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide this notifications object.
       * @example {
       *   "contractKeyFetched": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeyReturned": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractCreated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractStartReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractEndReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeysNotReturned": {
       *     "sms": false,
       *     "email": true
       *   },
       *   "contractUpdated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractSignatureRequested": {
       *     "sms": false,
       *     "email": false
       *   }
       * }
       */
      notifications?: components["schemas"]["ContactNotificationsDto"];
      /**
       * @description iLOQ person id
       * @example f5ac6bce-eac9-4508-a5cf-a0114dc06477
       */
      iloqPersonId?: string;
    };
    DefaultKeyContractDto: {
      /**
       * @description
       *   Type of contract: </br>
       *
       *   `1` = default </br>
       *   `2` = fetch </br>
       *   `3` = return </br>
       *
       * @example 1
       */
      contractType: number;
      /**
       * @description An array of iLOQ key access rights that will be programmed to the key when key is fetched
       * @example [
       *   "f5ac6bce-eac9-4508-a5cf-a0114dc06477"
       * ]
       */
      accessRightIds: string[];
      /**
       * @description Contact information of the recipient. The notifications field is optional and allows fine-grained control over notifications for different event types.
       *
       * IMPORTANT: When the notifications object is provided, the sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * BEST PRACTICES:
       * - Use the notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the contractKeysNotReturned notification.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide the notifications object.
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en",
       *   "iloqPersonId": "f5ac6bce-eac9-4508-a5cf-a0114dc06477",
       *   "notifications": {
       *     "contractKeyFetched": {
       *       "sms": true,
       *       "email": true
       *     },
       *     "contractCreated": {
       *       "email": true
       *     },
       *     "contractEndReminder": {
       *       "sms": true
       *     },
       *     "contractKeysNotReturned": {
       *       "sms": true,
       *       "email": false
       *     }
       *   }
       * }
       */
      contact?: components["schemas"]["ContactInput"];
      /**
       * @description Amount of keys needed for the handover. Required if keyAutomatId or groupId is provided
       * @example 2
       */
      numberOfKeys?: number;
      /**
       * @description Optional list of pincodes for the keys. If not provided, LivionKey will generate random pincodes for each key. Note that the amount of pincodes must match the amount of keys.
       * @example [
       *   "123455",
       *   "567822"
       * ]
       */
      pincodes?: string[];
      /**
       * @description Device group id, configured in LivionKey system
       * @example 64d35e0b57bbeb1658dd7a9b
       */
      groupId?: string;
      /**
       * @description Key automat device id from where the keys should be collected
       * @example 000111
       */
      keyAutomatId?: string;
      /** @description List of iLOQ key ids to be returned */
      keyIds?: string[];
      /**
       * Format: date-time
       * @description Start date of the contract. Mandatory for default and fetch only contracts.
       * @example 2022-02-16T08:20:00.000Z
       */
      start: string;
      /**
       * Format: date-time
       * @description End date of the contract. Mandatory if contract type is default, otherwise optional
       * @example 2022-02-16T08:20:00.000Z
       */
      end: string;
    };
    FetchKeyContractDto: {
      /**
       * @description
       *   Type of contract: </br>
       *
       *   `1` = default </br>
       *   `2` = fetch </br>
       *   `3` = return </br>
       *
       * @example 1
       */
      contractType: number;
      /**
       * @description An array of iLOQ key access rights that will be programmed to the key when key is fetched
       * @example [
       *   "f5ac6bce-eac9-4508-a5cf-a0114dc06477"
       * ]
       */
      accessRightIds: string[];
      /**
       * @description Contact information of the recipient. The notifications field is optional and allows fine-grained control over notifications for different event types.
       *
       * IMPORTANT: When the notifications object is provided, the sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * BEST PRACTICES:
       * - Use the notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the contractKeysNotReturned notification.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide the notifications object.
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en",
       *   "iloqPersonId": "f5ac6bce-eac9-4508-a5cf-a0114dc06477",
       *   "notifications": {
       *     "contractKeyFetched": {
       *       "sms": true,
       *       "email": true
       *     },
       *     "contractCreated": {
       *       "email": true
       *     },
       *     "contractEndReminder": {
       *       "sms": true
       *     },
       *     "contractKeysNotReturned": {
       *       "sms": true,
       *       "email": false
       *     }
       *   }
       * }
       */
      contact?: components["schemas"]["ContactInput"];
      /**
       * @description Amount of keys needed for the handover. Required if keyAutomatId or groupId is provided
       * @example 2
       */
      numberOfKeys?: number;
      /**
       * @description Optional list of pincodes for the keys. If not provided, LivionKey will generate random pincodes for each key. Note that the amount of pincodes must match the amount of keys.
       * @example [
       *   "123455",
       *   "567822"
       * ]
       */
      pincodes?: string[];
      /**
       * @description Device group id, configured in LivionKey system
       * @example 64d35e0b57bbeb1658dd7a9b
       */
      groupId?: string;
      /**
       * @description Key automat device id from where the keys should be collected
       * @example 000111
       */
      keyAutomatId?: string;
      /** @description List of iLOQ key ids to be returned */
      keyIds?: string[];
      /**
       * Format: date-time
       * @description Start date of the contract. Mandatory for default and fetch only contracts.
       * @example 2022-02-16T08:20:00.000Z
       */
      start: string;
    };
    ReturnKeyContractDto: {
      /**
       * @description
       *   Type of contract: </br>
       *
       *   `1` = default </br>
       *   `2` = fetch </br>
       *   `3` = return </br>
       *
       * @example 1
       */
      contractType: number;
      /**
       * @description Contact information of the recipient. The notifications field is optional and allows fine-grained control over notifications for different event types.
       *
       * IMPORTANT: When the notifications object is provided, the sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * BEST PRACTICES:
       * - Use the notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the contractKeysNotReturned notification.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide the notifications object.
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en",
       *   "iloqPersonId": "f5ac6bce-eac9-4508-a5cf-a0114dc06477",
       *   "notifications": {
       *     "contractKeyFetched": {
       *       "sms": true,
       *       "email": true
       *     },
       *     "contractCreated": {
       *       "email": true
       *     },
       *     "contractEndReminder": {
       *       "sms": true
       *     },
       *     "contractKeysNotReturned": {
       *       "sms": true,
       *       "email": false
       *     }
       *   }
       * }
       */
      contact?: components["schemas"]["ContactInput"];
      /**
       * @description Optional list of pincodes for the keys. If not provided, LivionKey will generate random pincodes for each key. Note that the amount of pincodes must match the amount of keys.
       * @example [
       *   "123455",
       *   "567822"
       * ]
       */
      pincodes?: string[];
      /**
       * @description Device group id, configured in LivionKey system
       * @example 64d35e0b57bbeb1658dd7a9b
       */
      groupId?: string;
      /**
       * @description Key automat device id from where the keys should be collected
       * @example 000111
       */
      keyAutomatId?: string;
      /**
       * Format: date-time
       * @description End date of the contract. Mandatory if contract type is default, otherwise optional
       * @example 2022-02-16T08:20:00.000Z
       */
      end: string;
      /** @description List of iLOQ key ids to be returned */
      keyIds: string[];
      /**
       * Format: date-time
       * @description Start date of the contract. If not provided, current date and time will be used.
       * @example 2022-02-16T08:20:00.000Z
       */
      start?: string;
    };
    HandoverIloqKeyBaseDto: {
      /**
       * @description
       *   Type of contract: </br>
       *
       *   `1` = default </br>
       *   `2` = fetch </br>
       *   `3` = return </br>
       *
       * @example 1
       */
      contractType: number;
      /**
       * @description An array of iLOQ key access rights that will be programmed to the key when key is fetched
       * @example [
       *   "f5ac6bce-eac9-4508-a5cf-a0114dc06477"
       * ]
       */
      accessRightIds: string[];
      /**
       * @description Contact information of the recipient. The notifications field is optional and allows fine-grained control over notifications for different event types.
       *
       * IMPORTANT: When the notifications object is provided, the sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * BEST PRACTICES:
       * - Use the notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the contractKeysNotReturned notification.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide the notifications object.
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en",
       *   "iloqPersonId": "f5ac6bce-eac9-4508-a5cf-a0114dc06477",
       *   "notifications": {
       *     "contractKeyFetched": {
       *       "sms": true,
       *       "email": true
       *     },
       *     "contractCreated": {
       *       "email": true
       *     },
       *     "contractEndReminder": {
       *       "sms": true
       *     },
       *     "contractKeysNotReturned": {
       *       "sms": true,
       *       "email": false
       *     }
       *   }
       * }
       */
      contact?: components["schemas"]["ContactInput"];
      /**
       * @description Amount of keys needed for the handover. Required if keyAutomatId or groupId is provided
       * @example 2
       */
      numberOfKeys?: number;
      /**
       * @description Optional list of pincodes for the keys. If not provided, LivionKey will generate random pincodes for each key. Note that the amount of pincodes must match the amount of keys.
       * @example [
       *   "123455",
       *   "567822"
       * ]
       */
      pincodes?: string[];
      /**
       * @description Device group id, configured in LivionKey system
       * @example 64d35e0b57bbeb1658dd7a9b
       */
      groupId?: string;
      /**
       * @description Key automat device id from where the keys should be collected
       * @example 000111
       */
      keyAutomatId?: string;
      /** @description List of iLOQ key ids to be returned */
      keyIds?: string[];
      /**
       * Format: date-time
       * @description Start date of the contract. Mandatory for default and fetch only contracts.
       * @example 2022-02-16T08:20:00.000Z
       */
      start: string;
      /**
       * Format: date-time
       * @description End date of the contract. Mandatory if contract type is default, otherwise optional
       * @example 2022-02-16T08:20:00.000Z
       */
      end: string;
    };
    CreateIloqKeyContractDto: {
      input: components["schemas"]["HandoverIloqKeyBaseDto"];
    };
    PaginationResponseDto: {
      after: string;
      limit: number;
      hasNext: boolean;
    };
    UpdateIloqContractDto: {
      /**
       * @description Contact information of the recipient. The notifications field is optional and allows fine-grained control over notifications for different event types.
       *
       * IMPORTANT: When the notifications object is provided, the sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * BEST PRACTICES:
       * - Use the notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the contractKeysNotReturned notification.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide the notifications object.
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en",
       *   "iloqPersonId": "f5ac6bce-eac9-4508-a5cf-a0114dc06477",
       *   "notifications": {
       *     "contractKeyFetched": {
       *       "sms": true,
       *       "email": true
       *     },
       *     "contractCreated": {
       *       "email": true
       *     },
       *     "contractEndReminder": {
       *       "sms": true
       *     },
       *     "contractKeysNotReturned": {
       *       "sms": true,
       *       "email": false
       *     }
       *   }
       * }
       */
      contact?: components["schemas"]["ContactInput"];
      /**
       * Format: date-time
       * @description Start date of the contract
       * @example 2022-02-16T08:20:00.000Z
       */
      start?: string;
      /**
       * Format: date-time
       * @description End date of the contract
       * @example 2022-02-16T08:20:00.000Z
       */
      end?: string;
    };
    IloqAccessRight: {
      /**
       * @description Access right id
       * @example fdef8481-98ad-42b8-b4b6-4eade261e281
       */
      id: string;
      /**
       * @description Access right name
       * @example Access right name
       */
      name: string;
      /**
       * @description Access right real estate path
       * @example Access right real estate path
       */
      realEstatePath: string | null;
    };
    AutomatLocation: {
      /** @description Street address of the automat */
      address: string | null;
      /**
       * @description Postal code the automat
       * @example 00100
       */
      postalCode: string | null;
      /**
       * @description Postal office of the automat
       * @example Helsinki
       */
      postalOffice: string | null;
    };
    AutomatGroup: {
      id: string;
      name: string;
    };
    AutomatLockerAssignedKey: {
      /** @description Key id */
      id: string;
      /** @description Key name */
      name: string;
    };
    AutomatLocker: {
      /** @description Index of the locker. Starts from 0. */
      lockerIndex: string;
      /** @description If key is present in the locker */
      isKeyInside: boolean;
      /** @description Assigned key information */
      key: components["schemas"]["AutomatLockerAssignedKey"] | null;
    };
    Automat: {
      id: string;
      name: string;
      /** @description Location of the automat */
      location: components["schemas"]["AutomatLocation"];
      /** @description Device specific label */
      label: string | null;
      /** @description Groups the automat belongs to */
      groups: readonly components["schemas"]["AutomatGroup"][];
      /** @description Hardware id of the automat */
      hwId: string | null;
      /** @description Timezone of the automat, format: TZ identifier */
      timezone: string | null;
      /** @description Installation pincode */
      installationPincode: string | null;
      /**
       * @description lockers of automat
       * @example [
       *   {
       *     "lockerIndex": "0",
       *     "isKeyInside": true,
       *     "key": {
       *       "id": "7c813082-8786-4a71-a3b5-30bf10004fe1",
       *       "name": "740FE4C"
       *     }
       *   },
       *   {
       *     "lockerIndex": "1",
       *     "isKeyInside": false,
       *     "key": null
       *   }
       * ]
       */
      lockers: readonly components["schemas"]["AutomatLocker"][];
      /** @description lifecycle state of the automat. Possible states: active, waitingForInstall. */
      lifecycleState: string | null;
    };
    InstallAutomatDto: {
      /** @description Logical name of the automat, for example:  Mainstreet 1 or headquarter */
      name: string;
      /** @description Install location organizationUnitId. */
      organizationUnitId?: string;
      /** @description Label is optional, used to identify more than one key automat from each other (typically A, B, C etc..….). */
      label?: string;
      /** @description Multiple key automats can be grouped, and then a key handover or return locker will be selected from key automats in a given group. */
      groupId?: string;
      /** @description Address of the automat */
      address: string;
      /** @description Postal code of the automat */
      postalCode: string;
      /** @description Postal office of the automat */
      postalOffice: string;
      /** @description Timezone of the automat. TZ identifier , for example: Europe/Helsinki */
      timezone: string;
      /**
       * @description Product identifier for the automat. Valid values are key20, key30.
       * @enum {string}
       */
      product: "key20" | "key30";
    };
    AutomatLocationDto: {
      /** @description Street address of the automat */
      address?: string;
      /**
       * @description Postal code the automat
       * @example 00100
       */
      postalCode?: string;
      /**
       * @description Postal office of the automat
       * @example Helsinki
       */
      postalOffice?: string;
    };
    UpdateAutomatDto: {
      /** @description name of the automat */
      name?: string;
      /** @description Device label */
      label?: string;
      /** @description An array of group ids */
      groups?: string[];
      /** @description Timezone of the automat, format: TZ identifier */
      timezone?: string;
      /** @description Location of the automat */
      location?: components["schemas"]["AutomatLocationDto"];
    };
    SendPincodeDto: {
      /** @description Pincode to be sent */
      pincode: string;
      /**
       * @description If true, pincode will be sent to the automat with proximity check. User will need to press hash key on the automat to open the locker.
       * @default false
       */
      proximityCheck?: boolean;
    };
    SendPincodeResponseDto: {
      /** @description If the command was sent successfully */
      success: boolean;
      /** @description Possible reason (if available) for failure in case success is false. For example AUTOMAT_BUSY. */
      reason: string | null;
    };
    CancelSendPincodeDto: {
      /** @description Pincode of the previously sent pincode to be cancelled. Only useful when proximity check was used for sending the pincode. */
      pincode: string;
    };
    CreateGroupDto: {
      name: string;
      customerId: string;
      /**
       * @description
       *   Allowed group types: </br>
       *   `1` = device </br>
       *   `2` = key </br>
       *
       * @example 1
       */
      type: number;
    };
    GroupMember: {
      id: string;
      name: string;
    };
    Group: {
      /** @description Group id */
      id: string;
      /** @description Group name */
      name: string;
      /** @description Group customer id */
      customerId: string | null;
      /**
       * @description Group type
       * @example 1
       */
      type: number;
      /** @description group members */
      members: readonly components["schemas"]["GroupMember"][];
    };
    UpdateGroupDto: {
      name?: string;
      customerId?: string;
    };
    IloqApiUserDto: {
      username: string;
      password: string;
      customerCode: string;
      serviceAddress: string;
    };
    CreateOrganizationUnitDto: {
      /**
       * @description
       *   Allowed Unit types: </br>
       *   `0` = organization (only allowed for special users) </br>
       *   `1` = country </br>
       * 	`2` = area </br>
       *   `3` = town </br>
       * 	`4` = district </br>
       * 	`5` = company </br>
       * 	`6` = other </br>
       *
       * @default 1
       */
      type: number;
      name: string;
      customerId: string;
      /** @description Parent organization unit id, used when creating sub organization unit */
      parentId?: string;
      iloqApiUser?: components["schemas"]["IloqApiUserDto"];
    };
    IloqApiUser: {
      username: string;
      password: string;
      customerCode: string;
      serviceAddress: string;
    };
    OrganizationUnit: {
      id: string;
      name: string;
      customerId: string | null;
      iloqApiUser: components["schemas"]["IloqApiUser"] | null;
      parentId: string | null;
      type: number;
    };
    CreateServiceAccountDto: {
      organizationUnitId: string;
      name: string;
    };
    ServiceAccount: {
      id: string;
      name: string;
      role: string;
      privateKey: string;
      organizationUnitId: string;
    };
    ContractContactInput: {
      /** @example John Doe */
      name: string;
      /** @example john.doe@livion.fi */
      email?: string;
      /** @example +358401234567 */
      phoneNumber?: string;
      /**
       * @description Boolean flag defining if SMS should be sent to the contact or not. Will use organization default notification settings to determine if SMS should be sent for each notification type. NOTE: This field is only used if the notifications object is NOT provided. If the notifications object is provided, this field is ignored.
       * @example true
       */
      sendSms?: boolean;
      /**
       * @description Boolean flag defining if Email should be sent to the contact or not. Will use organization default notification settings to determine if Email should be sent for each notification type. NOTE: This field is only used if the notifications object is NOT provided. If the notifications object is provided, this field is ignored.
       * @example true
       */
      sendEmail?: boolean;
      /**
       * @description Language code for the contact. Defines the language used for notifications. Defaults to "en" if not provided.
       * @default en
       * @example en | fi | sv | de | no | fr
       * @enum {string}
       */
      language?: "en" | "fi" | "sv" | "de" | "no" | "fr";
      /**
       * @description Detailed notification settings for different event types. This field is optional - you only need to provide it when you want granular control over notifications.
       *
       * IMPORTANT: When this object is provided, the global sendSms and sendEmail fields at the contact level are completely ignored.
       *
       * You can include only the specific notification types you want to customize. For notification types not included in this object, no notifications will be sent.
       *
       * You can also specify only sms or only email for each notification type - unspecified channels will default to false.
       *
       * BEST PRACTICES:
       * - Use this notifications object when a third-party system will handle sending notifications to end users.
       * - When using a third-party notification system, consider enabling at least the 'contractKeysNotReturned' notification to ensure keys are properly tracked.
       * - If you want LivionKey to handle notifications using organization defaults, use the global sendSms and sendEmail fields instead and do not provide this notifications object.
       * @example {
       *   "contractKeyFetched": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeyReturned": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractCreated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractStartReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractEndReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeysNotReturned": {
       *     "sms": false,
       *     "email": true
       *   },
       *   "contractUpdated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractSignatureRequested": {
       *     "sms": false,
       *     "email": false
       *   }
       * }
       */
      notifications?: components["schemas"]["ContactNotificationsDto"];
    };
    KeyFromAutomatInfoInput: {
      /**
       * @description Pincode to pick up the key from the automat. If not given, the system will generate a pincode.
       * @example 123456
       */
      pincode?: string;
      /**
       * @description The id of the automat. **Only required if the key is going to be handed from different storage than its current storage.**
       * @example automatId
       */
      automatId?: string;
    };
    KeyFromManualStorageInfoInput: {
      /**
       * @description Manual storage info if the key is stored in a manual storage. Example: "Shelf 1, Drawer 1". **Only required if the key is going to be handed from different storage than its current storage.**
       * @example Shelf 1, Drawer 1
       */
      manualStorageInfo?: string;
    };
    ContractKeyInput: {
      /**
       * @description The id of the key
       * @example keyId
       */
      id: string;
      storageInfo?: components["schemas"]["KeyFromManualStorageInfoInput"] | components["schemas"]["KeyFromAutomatInfoInput"];
    };
    CreateMechanicalKeyContractDto: {
      /**
       * Format: date-time
       * @description Start date of the contract.
       * @example 2025-02-16T08:20:00.000Z
       */
      start: string;
      /**
       * Format: date-time
       * @description End date of the contract.
       * @example 2025-02-16T08:20:00.000Z
       */
      end?: string | null;
      /**
       * @description Contact information of the recipient
       * @example {
       *   "name": "John Doe",
       *   "email": "john.doe@livion.fi",
       *   "phoneNumber": "+358401234567",
       *   "sendSms": true,
       *   "sendEmail": true,
       *   "language": "en"
       * }
       */
      contact: components["schemas"]["ContractContactInput"];
      /**
       * @description Verification method used. By default contract has no verification.   </br>`0` = No verification </br>
       * `1` = Signature via tablet/phone </br>
       * `2` = Strong Authentication (only available if the feature is enabled for the organization) </br>
       * @example 1
       */
      userVerification?: string | null;
      /**
       * @description Keys to be handed over.  </br>
       * KeyAutomat and manual storage keys cannot be mixed in the same contract.  </br>
       */
      keys: components["schemas"]["ContractKeyInput"][];
      /**
       * @description Required if manual storage key contract is in the future, This field can be used to give instructions to the user about where to pick up the key. This info will be used in notifications.**Only for future manual storage key contracts.**
       * @example Pick up the key from the reception desk. Reception is open from 8:00 to 16:00.
       */
      pickUpInfoForManualStorageKeys?: string | null;
      /**
       * @description By default, automat-fetched keys reserve the locker for the contract period. Set this field to true to release the locker immediately after key retrieval, making it available for other keys. **Only for automat key contracts**
       * </br> Keys can be received via Keyregister UI.</br>
       * @example false
       */
      freeLockerAfterFetch?: boolean | null;
      /** @description Contract identifier. The id needs to be unique for each contract. </br> If the contract id is provided, it will be used as the contract id. </br> If the contract id is not provided, system will generate a unique contract id. */
      id?: string | null;
    };
    CommonContractContact: {
      /** @example John Doe */
      name: string;
      /** @example john.doe@livion.fi */
      email: string | null;
      /** @example +358401234567 */
      phoneNumber: string | null;
      /**
       * @description Look for notifications object to check what SMS notifications are sent.
       * @example true
       */
      sendSms: boolean;
      /**
       * @description Look for notifications object to check what email notifications are sent.
       * @example true
       */
      sendEmail: boolean;
      /**
       * @description Language code for the contact. Defines the language used for notifications
       * @example en | fi | sv | de | no | fr
       * @enum {string|null}
       */
      language: "en" | "fi" | "sv" | "de" | "no" | "fr" | null;
      /**
       * @description Detailed notification settings that explicitly define which notifications will be sent and through which channels (SMS/email).
       * @example {
       *   "contractKeyFetched": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeyReturned": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractCreated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractStartReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractEndReminder": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractKeysNotReturned": {
       *     "sms": false,
       *     "email": true
       *   },
       *   "contractUpdated": {
       *     "sms": false,
       *     "email": false
       *   },
       *   "contractSignatureRequested": {
       *     "sms": false,
       *     "email": false
       *   }
       * }
       */
      notifications: components["schemas"]["ContactNotificationsDto"];
    };
    KeyFromAutomatInfo: {
      /**
       * @description Pincode to pick up the key from the automat. If not given, the system will generate a pincode.
       * @example 123456
       */
      pincode: string;
      /**
       * @description The id of the automat.
       * @example automatId
       */
      automatId: string;
    };
    KeyFromManualStorageInfo: {
      /**
       * @description Manual storage info if the key is stored in a manual storage. Example: "Shelf 1, Drawer 1"
       * @example Shelf 1, Drawer 1
       */
      manualStorageInfo: string;
    };
    ContractKey: {
      /**
       * @description The id of the key
       * @example keyId
       */
      id: string;
      storageInfo: components["schemas"]["KeyFromManualStorageInfo"] | components["schemas"]["KeyFromAutomatInfo"];
      /**
       * @description Status of the key
       * @example key-fetched
       */
      status?: string | null;
      /**
       * @description Boolean flag which indicates whether the key has been moved to history due to being fetched (fetch contracts), returned (return contracts), reassigned to a new contract, removed, or deactivated.
       *       If true, the key is in history and cannot be used anymore for this contract.
       * @example false
       */
      inHistory?: boolean;
    };
    MechanicalKeyContract: {
      /**
       * @description The id of the contract
       * @example 234567
       */
      id: string;
      /**
       * Format: date-time
       * @description Start date of the contract
       * @example 2025-02-16T08:20:00.000Z
       */
      start: string;
      /**
       * Format: date-time
       * @description End date of the contract. If not set, the contract is treated as permanent.
       * @example 2025-02-20T08:20:00.000Z
       */
      end: string | null;
      /** @description Contact information of the recipient */
      contact: components["schemas"]["CommonContractContact"] | null;
      /** @description List of keys */
      keys: readonly components["schemas"]["ContractKey"][];
      /** @description Boolean flag defining if the locker should be released after key retrieval. */
      freeLockerAfterFetch?: boolean | null;
      /**
       * @description 0 = No verification, 1 = Signature via tablet/phone ,  2 = Strong Authentication
       * @example 1
       */
      userVerification?: string;
      /** @description Required for future contracts, this field is be used to give instructions to the user about where to pick up the key. This info will be used in notifications. */
      pickUpInfoForManualStorageKeys?: string | null;
    };
    UpdateMechanicalKeyContractDto: {
      /**
       * Format: date-time
       * @description Start date of the contract.
       * @example 2025-02-16T08:20:00.000Z
       */
      start?: string | null;
      /**
       * Format: date-time
       * @description End date of the contract.
       * @example 2025-02-16T08:20:00.000Z
       */
      end?: string | null;
      /** @description Contact information of the recipient */
      contact?: components["schemas"]["ContractContactInput"] | null;
      /**
       * @description Verification method used. By default contract has no verification.   </br>`0` = No verification </br>
       * `1` = Signature via tablet/phone </br>
       * `2` = Strong Authentication (only available if the feature is enabled for the organization) </br>
       * </br>
       * Verification cannot be updated in following cases: </br>
       * - Contract has already been signed. </br>
       * - At least one key has already been fetched.
       *
       * @example 1
       */
      userVerification?: string | null;
      /**
       * @description Required if manual storage key contract is in the future, This field can be used to give instructions to the user about where to pick up the key. This info will be used in notifications.**Only for future manual storage key contracts.**
       * @example Pick up the key from the reception desk. Reception is open from 8:00 to 16:00.
       */
      pickUpInfoForManualStorageKeys?: string | null;
    };
    DeviceStorageDto: {
      /**
       * @description The id of the automat in case the key is stored in a key automat
       * @example automatId
       */
      automatId: string;
    };
    ManualStorageDto: {
      /**
       * @description Manual storage info if the key is stored in a manual storage. Example: "Shelf 1, Drawer 1"
       * @example Shelf 1, Drawer 1
       */
      manualStorageInfo: string;
    };
    CreateMechanicalKeyDto: {
      /**
       * @description The name of the key
       * @example Key 1
       */
      name?: string | null;
      /**
       * @description The organization unit id
       * @example 6347f74cba015bdbc2a36f97
       */
      organizationUnitId?: string | null;
      /**
       * @description The id of the key
       * @example KeyId
       */
      id: string;
      /**
       * @description RFID / NFC hex identifier. RFID will speed up key handover and return when separate USB RFID reader is used.
       * @example 1234567890
       */
      rfidHex?: string | null;
      /** @description Selected storage information where key is expect to be stored. */
      selectedStorage: components["schemas"]["DeviceStorageDto"] | components["schemas"]["ManualStorageDto"];
      /**
       * @description Allow overlapping contracts. Only for keys stored in a device. Default: false
       * @default false
       * @example false
       */
      shared?: boolean | null;
      /**
       * @description Whether the key is available or away at the moment of creation
       * @example false
       */
      away: boolean;
    };
    DeviceStorage: {
      /**
       * @description The id of the automat in case the key is stored in a key automat
       * @example DeviceId
       */
      automatId?: string;
    };
    ManualStorage: {
      /**
       * @description Manual storage info if the key is stored in a manual storage. Example: "Shelf 1, Drawer 1"
       * @example Shelf 1, Drawer 1
       */
      manualStorageInfo?: string;
    };
    KeyStatus: {
      /**
       * @description Whether the key is available or away
       * @example true
       */
      available: boolean;
    };
    MechanicalKey: {
      /**
       * @description The name of the key
       * @example KeyName
       */
      name?: string | null;
      /**
       * @description The organization unit id
       * @example OrganizationUnitId
       */
      organizationUnitId: string;
      /**
       * @description The id of the key
       * @example KeyId
       */
      id: string;
      /**
       * @description RFID / NFC hex identifier. RFID will speed up key handover and return when separate USB RFID reader is used.
       * @example 1A00D1
       */
      rfidHex?: string | null;
      /** @description Selected default storage information where key is expect to be stored */
      selectedStorage: components["schemas"]["DeviceStorage"] | components["schemas"]["ManualStorage"];
      /** @description Storage information of the key where it is currently stored. Null if key is away. */
      storage: components["schemas"]["DeviceStorage"] | components["schemas"]["ManualStorage"] | null;
      /** @description The storage location where the key is expected to be kept, either based on an active or upcoming contract or the key’s default assigned storage. This value is always present — even if the key is already in the correct place — and helps indicate where the key should be returned or stored. */
      targetStorage: components["schemas"]["DeviceStorage"] | components["schemas"]["ManualStorage"] | null;
      /** @description Whether the key is available or away */
      status: components["schemas"]["KeyStatus"];
      /**
       * @description Allow overlapping contracts. Only for keys stored in a device. Default: false
       * @example false
       */
      shared: boolean;
    };
    UpdateMechanicalKeyDto: {
      /**
       * @description The name of the key
       * @example Key 1
       */
      name?: string | null;
      /**
       * @description RFID / NFC hex identifier. RFID will speed up key handover and return when separate USB RFID reader is used.
       * @example 1234567890
       */
      rfidHex?: string | null;
      /** @description Selected storage information where key is expect to be stored. */
      selectedStorage?: components["schemas"]["DeviceStorageDto"] | components["schemas"]["ManualStorageDto"];
      /**
       * @description Allow overlapping contracts. Only for keys stored in a device. Default: false
       * @default false
       * @example false
       */
      shared?: boolean | null;
    };
    DeleteMechanicalKeyDto: {
      /**
       * @description Will delete all active contracts associated with the key
       * @example true
       */
      deleteActiveContracts?: boolean;
    };
  };
  responses: never;
  parameters: never;
  requestBodies: never;
  headers: never;
  pathItems: never;
}

export type $defs = Record<string, never>;

export type external = Record<string, never>;

export interface operations {

  /**
   * Get list of key contracts
   * @description Gets list of all contracts with pagination.
   */
  IloqController_getListOfContracts: {
    parameters: {
      query?: {
        /** @description Number of items to skip */
        after?: string;
        /**
         * @description Number of items to return. Default is 20, Max is 100.
         * @example 1
         */
        limit?: number;
        /**
         * @description Get ongoing contracts
         * @example true
         */
        ongoing?: boolean;
        /**
         * @description Get ended contracts
         * @example true
         */
        ended?: boolean;
        /**
         * @description Get future contracts
         * @example true
         */
        future?: boolean;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            after?: components["schemas"]["PaginationResponseDto"]["after"];
            limit?: components["schemas"]["PaginationResponseDto"]["limit"];
            hasNext?: components["schemas"]["PaginationResponseDto"]["hasNext"];
          } & {
            /** @description List of contracts */
            data?: components["schemas"]["IloqKeyContract"][];
          };
        };
      };
    };
  };
  /**
   * Create a key contract
   * @description
   *  Creates a contract which will be synced to device(s).</br>
   *  If notification flag(s) are enabled, notifications will also be sent to the user.</br>
   *
   *
   *  Contract type defines the type of contract to be created. Depending on the contract type, different fields are required. </br>
   *  Different types of contracts: </br>
   *   `1` = default </br>
   *   `2` = fetch </br>
   *   `3` = return </br>
   *
   *   When creating return type contract, keys will be added to the system if they do not exist. </br>
   *
   *  Select contractType to see required fields. </br>
   */
  IloqController_createContract: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateIloqKeyContractDto"];
      };
    };
    responses: {
      /** @description Contract has been successfully created */
      201: {
        content: {
          "application/json": components["schemas"]["IloqKeyContract"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description No device(s) with requested number of keys available for the handover */
      409: {
        content: never;
      };
    };
  };
  /** Get contract by id */
  IloqController_getContractById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Get contract by id */
      200: {
        content: {
          "application/json": components["schemas"]["IloqKeyContract"];
        };
      };
    };
  };
  /**
   * Delete a key contract by id.
   * @description
   *   Delete a contract by id. </br></b>
   *
   *   Restrictions:</br>
   *   **Default** contract cannot be deleted if any key has been fetched but not yet returned. </br>
   *   **Fetch-only** contract cannot be deleted if some keys have been fetched while others are still waiting to be fetched. </br>
   *   **Return-only** contract cannot be deleted if some keys have been returned while others are still waiting to be returned. </br>
   */
  IloqController_deleteContractById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Contract has been successfully deleted */
      204: {
        content: never;
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
    };
  };
  /**
   * Update a key contract by id
   * @description
   *  Partially update one or more fields of a contract. </br>
   */
  IloqController_updateContractById: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateIloqContractDto"];
      };
    };
    responses: {
      /** @description Contract has been successfully updated */
      200: {
        content: {
          "application/json": components["schemas"]["IloqKeyContract"];
        };
      };
      /** @description Bad Request */
      400: {
        content: never;
      };
      /** @description Overlapping contract */
      409: {
        content: never;
      };
    };
  };
  /** Get list of access rights */
  IloqController_getAccessRights: {
    parameters: {
      query?: {
        /** @description Number of items to skip */
        after?: string;
        /**
         * @description Number of items to return. Default is 20, Max is 100.
         * @example 1
         */
        limit?: number;
        /**
         * @description Return only access rights which are displayed by default in iLOQ manager
         * @example false
         */
        returnDefaultAccessesOnly?: boolean;
        /**
         * @description Search for access rights by name
         * @example test
         */
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            after?: components["schemas"]["PaginationResponseDto"]["after"];
            limit?: components["schemas"]["PaginationResponseDto"]["limit"];
          } & {
            /** @description List of access rights */
            data?: components["schemas"]["IloqAccessRight"][];
          };
        };
      };
    };
  };
  /** Get list of automats */
  AutomatsController_getAutomats: {
    parameters: {
      query?: {
        /** @description Number of items to skip */
        after?: string;
        /**
         * @description Number of items to return. Default is 20, Max is 100.
         * @example 1
         */
        limit?: number;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            after?: components["schemas"]["PaginationResponseDto"]["after"];
            limit?: components["schemas"]["PaginationResponseDto"]["limit"];
            hasNext?: components["schemas"]["PaginationResponseDto"]["hasNext"];
          } & {
            /** @description List of automats */
            data?: components["schemas"]["Automat"][];
          };
        };
      };
    };
  };
  /** Get automat by id */
  AutomatsController_getAutomatById: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Get automat by id */
      200: {
        content: {
          "application/json": components["schemas"]["Automat"];
        };
      };
      /** @description Automat not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Update automat
   * @description Updates automat information
   */
  AutomatsController_updateAutomat: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateAutomatDto"];
      };
    };
    responses: {
      /** @description Updated automat */
      200: {
        content: {
          "application/json": components["schemas"]["Automat"];
        };
      };
    };
  };
  /**
   * Install automat
   * @description Installs a new key automat to LivionKey system.
   */
  AutomatsController_installAutomat: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["InstallAutomatDto"];
      };
    };
    responses: {
      /** @description Installed automat */
      201: {
        content: {
          "application/json": components["schemas"]["Automat"];
        };
      };
    };
  };
  /**
   * Uninstall automat.
   * @description Sets device lifecycle state to deactivated.
   */
  AutomatsController_uninstallAutomat: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Uninstalled automat */
      204: {
        content: never;
      };
    };
  };
  /**
   * Replace automat
   * @description Replaces automat hwId with a new one
   */
  AutomatsController_replaceAutomat: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Replaced automat */
      200: {
        content: {
          "application/json": components["schemas"]["Automat"];
        };
      };
    };
  };
  /**
   * Send pincode
   * @description Sends a pincode to the Key Automat.
   *     If the pincode matches one stored in the automat, the corresponding locker will open.
   *     In case of iLOQ S5 keys, the key will also be programmed with the access rights defined in the contract.
   */
  AutomatsController_sendPincode: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["SendPincodeDto"];
      };
    };
    responses: {
      /** @description Command sent successfully */
      200: {
        content: {
          "application/json": components["schemas"]["SendPincodeResponseDto"];
        };
      };
      /** @description Bad request */
      400: {
        content: never;
      };
      /** @description Automat not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Cancel send pincode
   * @description Cancels a pincode send to the automat or any ongoing proximity check.
   *     Typically used to cancel previously sent sendPincode command with proximityCheck: true
   */
  AutomatsController_cancelSendPincode: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["CancelSendPincodeDto"];
      };
    };
    responses: {
      /** @description Command sent successfully */
      200: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: never;
      };
      /** @description Automat not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Get list of groups
   * @description Gets list of all groups with pagination.
   */
  GroupsController_list: {
    parameters: {
      query?: {
        /** @description Number of items to skip */
        after?: string;
        /**
         * @description Number of items to return. Default is 20, Max is 100.
         * @example 1
         */
        limit?: number;
        customerId?: string;
        search?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            after?: components["schemas"]["PaginationResponseDto"]["after"];
            limit?: components["schemas"]["PaginationResponseDto"]["limit"];
            hasNext?: components["schemas"]["PaginationResponseDto"]["hasNext"];
          } & {
            /** @description List of groups */
            data?: components["schemas"]["Group"][];
          };
        };
      };
    };
  };
  /** Create a new group */
  GroupsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateGroupDto"];
      };
    };
    responses: {
      /** @description Group has been successfully created */
      201: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
    };
  };
  /** Get group by id */
  GroupsController_findOne: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Get group by id */
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description group not found */
      404: {
        content: never;
      };
    };
  };
  /** Delete a group by id */
  GroupsController_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Group has been successfully deleted */
      204: {
        content: never;
      };
      /** @description Group not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Update group
   * @description Updates group information
   */
  GroupsController_update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateGroupDto"];
      };
    };
    responses: {
      /** @description Updated group */
      200: {
        content: {
          "application/json": components["schemas"]["Group"];
        };
      };
      /** @description Group not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Create a new organization unit
   * @description Create different types of organization units
   */
  OrganizationUnitsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateOrganizationUnitDto"];
      };
    };
    responses: {
      /** @description Organization Unit has been successfully created */
      201: {
        content: {
          "application/json": components["schemas"]["OrganizationUnit"];
        };
      };
    };
  };
  /**
   * Create a service account
   * @description Create a service account for organization unit. Note that the private key will be only shown once.
   */
  ServiceAccountsController_create: {
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateServiceAccountDto"];
      };
    };
    responses: {
      /** @description Service account has been successfully created */
      201: {
        content: {
          "application/json": components["schemas"]["ServiceAccount"];
        };
      };
    };
  };
  /** Delete a service account by id */
  ServiceAccountsController_delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description Service account has been successfully deleted */
      204: {
        content: never;
      };
      /** @description Service account not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Paginated list of keys
   * @description Paginated list of keys
   */
  list: {
    parameters: {
      query?: {
        /** @description Number of items to skip */
        after?: string;
        /**
         * @description Number of items to return. Default is 20, Max is 100.
         * @example 1
         */
        limit?: number;
        /**
         * @description Search for keys by keyword
         * @example 123
         */
        search?: string;
        /**
         * @description Selected storage filter. Returns list of keys based on their set selectedStorage. </br>`1` = Device keys </br>`2` = Manual keys
         * @example 1
         */
        selectedStorage?: string;
        /**
         * @description Filters keys with specific automat as their selected storage
         * @example 223567
         */
        automatId?: string;
        /**
         * @description Filter keys belonging to a specific organization unit
         * @example 223567
         */
        organizationUnitId?: string;
      };
    };
    responses: {
      200: {
        content: {
          "application/json": {
            after?: components["schemas"]["PaginationResponseDto"]["after"];
            limit?: components["schemas"]["PaginationResponseDto"]["limit"];
            hasNext?: components["schemas"]["PaginationResponseDto"]["hasNext"];
          } & {
            /** @description Get list of keys with pagination */
            data?: components["schemas"]["MechanicalKey"][];
          };
        };
      };
    };
  };
  /**
   * Create a mechanical key
   * @description Create a mechanical key
   */
  create: {
    /** @description Create a mechanical key */
    requestBody: {
      content: {
        "application/json": components["schemas"]["CreateMechanicalKeyDto"];
      };
    };
    responses: {
      /** @description The key has been successfully created */
      201: {
        content: {
          "application/json": components["schemas"]["MechanicalKey"];
        };
      };
      /** @description Bad request */
      400: {
        content: never;
      };
      /** @description Key already exists with the same keyId */
      409: {
        content: never;
      };
    };
  };
  /**
   * Get a key by id
   * @description Get a key by id
   */
  get: {
    parameters: {
      path: {
        id: string;
      };
    };
    responses: {
      /** @description The key has been successfully fetched */
      200: {
        content: {
          "application/json": components["schemas"]["MechanicalKey"];
        };
      };
      /** @description Key not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Delete a key by id
   * @description Delete a key by id
   */
  delete: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["DeleteMechanicalKeyDto"];
      };
    };
    responses: {
      /** @description The key has been successfully deleted */
      204: {
        content: never;
      };
      /** @description Bad request */
      400: {
        content: never;
      };
      /** @description Key not found */
      404: {
        content: never;
      };
    };
  };
  /**
   * Update a key by id
   * @description Update a key by id
   */
  update: {
    parameters: {
      path: {
        id: string;
      };
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["UpdateMechanicalKeyDto"];
      };
    };
    responses: {
      /** @description The key has been successfully updated */
      200: {
        content: {
          "application/json": components["schemas"]["MechanicalKey"];
        };
      };
      /** @description Bad request */
      400: {
        content: never;
      };
      /** @description Key not found */
      404: {
        content: never;
      };
    };
  };
}
